name: Build Hexo Site

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        ref: 'dev'

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Install app dependencies
      run: |
        npm install -g hexo-cli
        npm install

    - name: Build
      run: |
        npm run clean
        npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.PAT }}
        branch: gh-pages
        folder: public